apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-frontend.yaml
  - deployment-backend.yaml
  - service-frontend.yaml
  - service-backend.yaml
  - ingress.yaml
